"""matching column

Revision ID: 1a8075c9f785
Revises: add_recent_image_cols
Create Date: 2025-12-29 23:35:35.293131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a8075c9f785'
down_revision: Union[str, None] = 'add_recent_image_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.add_column('users', sa.Column('matching_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'matching_percentage')
    op.create_table('profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('academic_background', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profession', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hobbies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medical_history', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overall_health_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_term_condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_term_condition_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genetic_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fertility_awareness', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disability', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disability_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dietary_preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smoking_habit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alcohol_consumption', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chronic_illness', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interests', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_age_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_age_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_height_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preferred_height_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preferred_weight_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preferred_weight_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preferred_religion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_education', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_profession', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specific_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('willing_to_relocate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lifestyle_pref_smoking', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lifestyle_pref_alcohol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lifestyle_pref_dietary_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('living_with_in_laws', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('career_support_expectations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('necessary_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('intro_video_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('intro_video_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intro_video_content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medical_documents_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('medical_documents_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medical_documents_content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_picture_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('profile_picture_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_picture_content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey'),
    sa.UniqueConstraint('user_id', name='profiles_user_id_key')
    )
    # ### end Alembic commands ###
