"""Add user profile fields for signup

Revision ID: 8a6025fe2402
Revises: e0e0fd4185a6
Create Date: 2025-10-25 20:06:13.222595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6025fe2402'
down_revision: Union[str, None] = 'e0e0fd4185a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('users', sa.Column('nid', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_age_from', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferred_age_to', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['nid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'preferred_age_to')
    op.drop_column('users', 'preferred_age_from')
    op.drop_column('users', 'religion')
    op.drop_column('users', 'age')
    op.drop_column('users', 'nid')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
