"""Add is_admin column to users table

Revision ID: e0e0fd4185a6
Revises: 0f72bc3ab804
Create Date: 2025-10-24 16:40:49.048539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e0fd4185a6'
down_revision: Union[str, None] = '0f72bc3ab804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    # Make the column non-nullable
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
